#!/bin/bash

# Conky start-up delay script for \LCARS\LMGX\0.02x\:
# Configured at install, so if it's not loading right,
# check the accompaning lcarsrc copied at install.

source /usr/share/lcars_gx/lcarsrc

# Needed for xfce to force this img as root of X
qiv --root /usr/share/backgrounds/lcars_gx/default_lcars_gx.jpg

sleep 20 &&
conky -c /home/notroot/.conkyrc &
sleep 20 &&
conky -c /home/notroot/.lcars_gx/.conkyrc_logs &

exit 0